apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-boot-demo-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: k8s-boot-demo
  template:
    metadata:
      labels:
        app: k8s-boot-demo
    spec:
      containers:
        - name: k8s-boot-demo
          image: saravankumar/k8s:v1
          ports:
            - containerPort: 8080
            readinessProbe:
              httpGet:
                port: 8080
                path: /actuator/health/readiness
              livenessProbe:
                httpGet:
                  port: 8080
                  path: /actuator/health/liveness
              startupProbe:
                initialDelaySeconds: 5
                httpGet:
                  port: 8080
                  path: /actuator/health/liveness

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-boot-demo-service
spec:
  type: NodePort
  selector:
    app: k8s-boot-demo
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090